### PR TITLE
Made some changes Adrian asked for.

### PR DESCRIPTION
**Pull request by nigelgbanks**
Includes some name-spacing for html level elements.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
@jamescummings Hi James would you mind taking a quick look at the changes I've made, and merge them if it works for you.

**Comment by nigelgbanks** [comment]
oh I forgot about this. @awisnicki, had been making changes to the transcription.xsl and style.css files recently, looks like the merge didn't go well.

https://github.com/livingstoneonline/LEAP-XSLT/blob/gh-pages/transcription.xsl#L2

I'm going to revert the changes merged here if possible.

**Comment by nigelgbanks** [comment]
I reverted this pull with the commit https://github.com/livingstoneonline/LEAP-XSLT/commit/b63b7ed8368e80415dc5e480a207d3116b3aa837.

**Comment by jamescummings** [comment]
I thought that might be the case. Apologies... there was 
absolutely nothing wrong in the changes, of course, I just forgot 
about them and then went and merged them... tried to manually 
detangle the conflicts but looks like editing has gone on since.

-James

On 06/06/16 12:52, Nigel Banks wrote:

> oh I forgot about this. @awisnicki 
> https://github.com/awisnicki, had been making changes to the 
> transcription.xsl and style.css files recently, looks like the 
> merge didn't go well.
> 
> https://github.com/livingstoneonline/LEAP-XSLT/blob/gh-pages/transcription.xsl#L2
> 
> I'm going to revert the changes merged here if possible.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> https://github.com/livingstoneonline/LEAP-XSLT/pull/1#issuecomment-224068630, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AASGy5Wbg-7X2kGzu5aLxW8MoY0NQzxGks5qJHqYgaJpZM4Iibiz.

## 

Dr James Cummings, James.Cummings@it.ox.ac.uk
Academic IT Services, University of Oxford

**Comment by awisnicki** [comment]
Nigel, did this have to do with the xsl and css files that I've been updating? If so, then I've completely overhauled them top to bottom and the versions I've put up in here recently (and which I can copy over again if necessary -- let me know) are the ones we should be using. They supercede all other versions.

**Comment by nigelgbanks** [comment]
@awisnicki no worries I reverted the merge so things are now as you had them last.

**Comment by awisnicki** [comment]
OK, great. Thank you. I'll be getting you a new files soon that incorporate the padding, etc changes that you suggested.

**Pull request merged**
